# Generated by Django 2.1.7 on 2020-02-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200222_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.TextField(default='Regular User'),
        ),
    ]
