# Generated by Django 2.1.7 on 2023-06-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230606_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudy',
            name='host_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank_point',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank_tear',
        ),
        migrations.DeleteModel(
            name='GroupStudy',
        ),
    ]
