# Generated by Django 5.2.5 on 2026-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_sso_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='unknown', max_length=255, verbose_name='Username')),
                ('login_date', models.DateField(auto_now_add=True, verbose_name='Login Date')),
            ],
            options={
                'db_table': 'user_login_history',
            },
        ),
    ]
