# Generated by Django 2.1.7 on 2020-02-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200222_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isstudent',
            field=models.BooleanField(default=False),
        ),
    ]
