# Generated by Django 2.1.7 on 2023-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230628_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schoolssn',
            field=models.TextField(null=True),
        ),
    ]
