# Generated by Django 2.1.7 on 2020-02-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_isstudent'),
        ('account', '0003_auto_20200222_0703'),
    ]

    operations = [
    ]
