# Generated by Django 2.1.7 on 2020-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20200222_1034'),
    ]

    operations = [
    ]
