# Generated by Django 2.1.7 on 2020-03-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isstudent',
        )
    ]
