# Generated by Django 5.2.5 on 2026-02-26 07:11

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', utils.models.RichTextField()),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('status', models.BooleanField()),
                ('aihelper_status', models.BooleanField(default=False)),
                ('password', models.TextField()),
                ('isapply', models.BooleanField(default=False)),
                ('isallow', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecture',
            },
        ),
        migrations.CreateModel(
            name='signup_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('isallow', models.BooleanField(default=False)),
                ('realname', models.TextField(default=None, null=True)),
                ('schoolssn', models.IntegerField(default=None, null=True)),
                ('score', models.JSONField(default=dict)),
                ('etc', models.TextField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ta_admin_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.TextField(default=None, null=True)),
                ('schoolssn', models.IntegerField(default=None, null=True)),
                ('lecture_isallow', models.BooleanField(default=False)),
                ('code_isallow', models.BooleanField(default=False)),
                ('score_isallow', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
