# Generated by Django 2.1.7 on 2020-02-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
    ]
