# Generated by Django 2.1.7 on 2020-08-12 05:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='permit_to',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
