# Generated by Django 2.2.16 on 2020-09-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_signup_class_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_class',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
