# Generated by Django 2.1.7 on 2020-02-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20200209_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_class',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='signup_class',
            old_name='user_id',
            new_name='user',
        ),
    ]
