# Generated by Django 2.1.7 on 2020-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20200209_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_class',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
