# Generated by Django 2.1.7 on 2023-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20200922_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='aihelper_status',
            field=models.BooleanField(default=False),
        ),
    ]
