# Generated by Django 2.1.7 on 2020-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_signup_class_status'),
    ]

    operations = [
    ]
