# Generated by Django 2.1.7 on 2020-02-20 16:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20200214_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='allowed_ip_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
