# Generated by Django 2.1.7 on 2020-02-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lecture_allowed_ip_ranges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='allowed_ip_ranges',
            new_name='contestlist',
        ),
    ]
