# Generated by Django 2.1.7 on 2020-02-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_lecture_contest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecture_contest',
            table='lecture_contest',
        ),
    ]
