# Generated by Django 2.1.7 on 2020-02-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_auto_20200220_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='contestlist',
        ),
    ]
