# Generated by Django 2.1.7 on 2020-02-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_remove_lecture_contestlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture_contest',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='lecture_contest',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='lecture_contest',
        ),
    ]
