# Generated by Django 2.1.7 on 2020-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_lecture_isapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='isapply',
        ),
        migrations.AddField(
            model_name='signup_class',
            name='apply_user',
            field=models.BooleanField(default=False),
        ),
    ]
