# Generated by Django 2.1.7 on 2020-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0015_auto_20200222_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='isallow',
            field=models.BooleanField(default=False),
        ),
    ]
