# Generated by Django 2.1.7 on 2020-03-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_lecture_isallow'),
    ]

    operations = [
    ]
