# Generated by Django 2.1.7 on 2020-03-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_lecture_isallow'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_class',
            name='realname',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='signup_class',
            name='schoolssn',
            field=models.IntegerField(default=None),
        ),
    ]
