# Generated by Django 2.1.7 on 2020-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0018_auto_20200310_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_class',
            name='realname',
            field=models.TextField(null=True),
        ),
    ]
