# Generated by Django 2.1.7 on 2020-03-10 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_auto_20200311_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_class',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
