# Generated by Django 2.1.7 on 2020-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0022_auto_20200311_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_class',
            name='realname',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='signup_class',
            name='schoolssn',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
