# Generated by Django 2.1.7 on 2020-03-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0023_auto_20200311_0051'),
    ]

    operations = [
    ]
