# Generated by Django 2.1.7 on 2020-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0024_auto_20200311_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_class',
            name='etc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='signup_class',
            name='score',
            field=models.TextField(null=True),
        ),
    ]
