# Generated by Django 2.1.7 on 2020-03-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0025_auto_20200312_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_class',
            name='apply_user',
        ),
    ]
