# Generated by Django 2.1.7 on 2022-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20200922_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='proceeding',
            field=models.BooleanField(default=True),
        ),
    ]
