# Generated by Django 2.1.7 on 2020-02-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_lecture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='lecture_id',
            new_name='lecture',
        ),
    ]
