# Generated by Django 2.1.7 on 2020-02-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20200226_1317'),
    ]

    operations = [
    ]
