# Generated by Django 2.1.7 on 2020-03-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20200226_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lecture_id',
        ),
    ]
