# Generated by Django 2.1.7 on 2020-02-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20200209_0538'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='assigned_lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
