# Generated by Django 5.2.5 on 2026-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='llm_hint_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
