# Generated by Django 2.1.7 on 2020-02-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_assigned_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='assigned_lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
