# Generated by Django 2.1.7 on 2022-03-29 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_contestsubmituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contestsubmituser',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestsubmituser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContestSubmitUser',
        ),
    ]
