# Generated by Django 2.1.7 on 2020-02-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20200213_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='assigned_lecture',
        ),
    ]
