# Generated by Django 2.1.7 on 2022-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20220329_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestuser',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='contestuser',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contestuser',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
