# Generated by Django 2.1.7 on 2020-02-21 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_auto_20200221_0438'),
        ('contest', '0004_remove_contest_assigned_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
