# Generated by Django 2.1.7 on 2020-02-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='lecture',
            new_name='lecture_id',
        ),
    ]
