# Generated by Django 2.1.7 on 2022-04-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20220407_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestuser',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
