# Generated by Django 2.1.7 on 2020-02-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20200221_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='lecture_id',
            new_name='lecture',
        ),
    ]
