# Generated by Django 2.1.7 on 2020-02-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20200221_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
