# Generated by Django 2.1.7 on 2020-02-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20200224_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='lecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
