# Generated by Django 5.2.5 on 2026-02-26 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('key_prefix', models.CharField(db_index=True, max_length=20)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('total_prompt_tokens', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_api_key',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LLMAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='llm.llmapikey')),
            ],
            options={
                'db_table': 'llm_audit_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LLMChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_chat_session',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LLMChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.llmchatsession')),
            ],
            options={
                'db_table': 'llm_chat_message',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='LLMRouteMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('upstream_url', models.CharField(max_length=1024)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('weight', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_route_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_route_map',
                'ordering': ('model_name', 'priority', '-weight', 'upstream_url'),
            },
        ),
    ]
